# Generated by Django 3.2 on 2023-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nac_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('pud_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
